# Generated by Django 4.1.6 on 2023-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_role_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="body",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="header",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
