# Generated by Django 4.1.6 on 2023-05-22 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_body_task_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="header",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="executor",
            new_name="assignee",
        ),
    ]
