# Generated by Django 4.1.6 on 2023-08-18 12:03

from django.db import migrations, models
import main.services.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_user_avatar_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=main.services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
