name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Up container
        run: docker-compose --file docker-compose.ci.yml up -d

      - name: Run tests
        run: docker compose exec api make test
      
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop