name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: coveralls
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
        run: docker-compose --file docker-compose.ci.yml run --rm api make test COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" EMAIL_HOST_PASSWORD="$EMAIL_HOST_PASSWORD"